import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'

export default defineConfig({
  plugins: [
    react({
      // Use classic JSX runtime to avoid jsx-runtime externalization issues
      jsxRuntime: 'classic',
    }),
  ],

  // Define environment variables for browser
  define: {
    'process.env.NODE_ENV': JSON.stringify('production'),
  },

  build: {
    lib: {
      entry: resolve(__dirname, 'src/jsx/dataset-search-widget.jsx'),
      formats: ['iife'],
      name: 'DkanDatasetSearchWidget',
    },

    outDir: 'js',
    emptyOutDir: false,

    rollupOptions: {
      // Externalize DKAN Client Tools React (self-contained with React, ReactDOM, React Query)
      // Using classic JSX runtime to avoid jsx-runtime externalization issues
      external: [
        '@dkan-client-tools/react',
        '@dkan-client-tools/core',
      ],

      output: {
        entryFileNames: 'dataset-search-widget.min.js',

        // Map external modules to their window globals (without 'window.' prefix)
        // Rollup generates: (function(DkanClientToolsReact) {...})(window.DkanClientToolsReact)
        globals: {
          '@dkan-client-tools/react': 'DkanClientToolsReact',
          '@dkan-client-tools/core': 'DkanClientTools',
        },

        // Add banner
        banner: `/**
 * DKAN Dataset Search Widget
 *
 * Built with Vite (IIFE format)
 * DkanClientToolsReact provided by dkan_client_tools_react_base module
 *
 * Do not edit this file - edit src/jsx/dataset-search-widget.jsx
 */`,
      },
    },

    // Minify with terser
    minify: 'terser',
    sourcemap: true,
  },
})
